### ISSUE TITLE
全局封禁Rose, Rei

### ISSUE THREAD

**Issue by wfjsw** [wfjsw/PeaceManager#1]
Rose, Rei将被加入PeaceManager全局硬封禁列表
用户信息：
User id: 68256164
First name: Rei
Username: @commonlisp

User id: 53835259
First name: Rose
Username: @iwakuralain

该设定同时应用于 wfjsw/PeaceManager-Lite

**Comment by yazeed44** [comment]
I think simon suggested a list for global ban before , maybe you could ask him

**Comment by wfjsw** [comment]
May use feeds later
